# Generated by Django 3.2.12 on 2022-07-01 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20220701_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 1, 17, 47, 50, 840783)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 7, 1, 17, 47, 50, 840813)),
        ),
    ]
